### ISSUE TITLE
How to train personal data

### ISSUE THREAD

**Issue by mangomqy** [dadukhankevin/Finch#4] opened 2023-07-04 15:03 UTC
Hi @dadukhankevin , Thanks for sharing the wonderful framework. However, I have trouble in using personal data to train and test. For example, how do I using Finch to process iris dataset, stored in a 150x4 numpy.ndarray

**Comment by mangomqy** [comment] 2023-07-04 16:40
Hi @dadukhankevin , when I run the examples/basic.py, I got some mistakes.
```
  File "cupy/_core/core.pyx", line 2360, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2384, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2512, in cupy._core.core._array_default
ValueError: Unsupported dtype <U1
```

**Comment by dadukhankevin** [comment] 2023-07-05 02:27
Hi, are you running on a GPU? 
I'm using numpy for cpu and Cupy is automatically used when you have a GPU, the problem is that cupy doesn't support any datatypes that aren't floats (at least thats my best guess).
Also, generally a 1 dimensional array is best, you can use things like ```np.reshape``` to make it 150x4 in the fitness function, but otherwise keep it flat. 
If that doesn't make sense would you mind sharing your code?
Good luck!

**Comment by dadukhankevin** [comment] 2023-07-05 06:19
I was thinking about this a bit more and realized:
- You should defiantly flatten the array (and simply reshape it in your fitness function)
- I really need to add a way to manually specify using Numpy and not Cupy (but I don't think that's necessarily causing your problem).
Finch is still pretty new so thanks for trying it out!
Out of curiosity, what are you trying to make?

**Comment by mangomqy** [comment] 2023-07-05 07:55
> 

Thanks, @dadukhankevin. I trying to classify the IRIS dataset using GA. Finch is the fastest GA framework I saw. However, I still not clear to use it. 
A iris dataframe(iris_df) like this:
``````
     col0  col1  col2  col3  target
0     5.1   3.5   1.4   0.2       0
1     4.9   3.0   1.4   0.2       1
2     4.7   3.2   1.3   0.2       0
3     4.6   3.1   1.5   0.2       1
4     5.0   3.6   1.4   0.2       0
``````
How do I train the data and make predictions?

**Comment by dadukhankevin** [comment] 2023-07-05 09:50
Ah, I see. I'm still working on better ML support to evolve AI model weights (aka neuroevolution). Sadly I haven't been able to test it very much yet... 
however, you should be able to do it using the ```KerasPool``` gene pool class found in ```Finch.ml.KerasPool```. Then you can define your keras model:
```python
model = keras.Sequential(...your keras model...)
# now define the gene pool
gene_pool = Finch.ml.KerasPool(model, fitness_function)
# This gene pool will handle flattening and unflattening the keras weights automatically to do this use:
new_fitness_function = gene_pool.fitness_function_wrapped
# this will execute the fitness function you gave in the proper way
```
Now in for your fitness function (and here I'm just guessing) you would need something like this
```python
def fitness_function(model):
    fitness = model.evaluate(x_train, y_train, batch_size=<whatever>)[0] # [0] for loss and [1] for accuracy if your using loss make sure to make it negative (fitness functions need to return higher numbers for better individuals), you could also combine them...
    return fitness```
This would be the fitness function you would then pass to your KerasPool.
I hope this helps, this week I plan on working a lot on the whole ML side of Finch  and it should work much better. I'll also add colab notbooks with examples soon.

**Comment by dadukhankevin** [comment] 2023-07-05 09:51
you will also need to have keras, tensorflow, and pytorch installed (for now)

**Comment by dadukhankevin** [comment] 2023-07-19 04:12
I'm going to close this since there hasn't been any further activity. I am actively working on better ML support.

**Closed by dadukhankevin** 2023-07-19 04:12 UTC
